name: Generate GitHub Stats SVGs

on:
  schedule:
    - cron: '0 0 * * *' # roda todo dia Ã  meia-noite
  workflow_dispatch: # permite rodar manualmente
  push:
    branches:
      - main # ou master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@v0.2.3
        with:
          username: TamiresMusafir
          show_icons: true
          theme: radical
          hide_border: true
          output_path: output/github-stats.svg

      - name: Generate Top Languages
        uses: anuraghazra/github-readme-stats@v0.2.3
        with:
          username: TamiresMusafir
          theme: radical
          mode: top-langs
          hide_border: true
          output_path: output/top-langs.svg

      - name: Commit and push SVGs
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Update GitHub stats SVGs"
          add: "output/*"
